### ISSUE TITLE
OpenID Connect + JSON Web Token support

### ISSUE THREAD

**Issue by aew** [pelle/clauth#15]
Looking for a perspective from the maintainer - Is support for the OpenID Connect standard for authentication (built on top of OAuth 2.0), and loosely related support for JSON web tokens (JWT, JWS, JWE) something interesting for Clauth to support going forward? Would pull requests be interesting, or does this belong in a separate library in your opinion?

**Comment by pelle** [comment]
I think it would work well. Have been thinking about it for a while as well.

I think that the web token support would probably be best in a separate library, but for ease of development feel free to leave it in a separate namespace for now.

If it can be done cleanly which I think it can I think it makes sense for it to be part of clauth. Please take a stab at it.

**Comment by aew** [comment]
Ok thanks.  Will see when we can clean things up enough to send a pull request - closing for now.

**Comment by ryfow** [comment]
@aew We'd be interested in helping with this. If that's feasible, let me know.
